name: Deploy to Heroku

on:
  push:
    branches:
      - production  # Trigger for production deployment
      - development  # Trigger for development (testing only)

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'  # Only run tests for development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # or your PHP version

      - name: Install Composer dependencies
        run: composer install -q --no-interaction --prefer-dist --optimize-autoloader --no-progress

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit

  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'  # Only deploy to Heroku on production branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # or your PHP versionu

      - name: Update Composer
        run: composer update
            
      - name: Install Composer dependencies
        run: composer install -q --no-interaction --prefer-dist --optimize-autoloader --no-progress

      - name: Set up Git user identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch from Heroku
        if: success()
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
            git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/stock-management-system.git
            git fetch heroku production
            git rebase -X theirs heroku/production

      - name: Continue rebase if necessary
        run: git rebase --continue || echo "No rebase needed"

      - name: Deploy to Heroku
        if: success()
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
            git push heroku production --force
